server:
  port: 8088


mysql:
    driver: com.mysql.jdbc.Driver
    maxActive: 20
    oldlangying:
            url: jdbc:mysql://192.168.12.252:3306/langying?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
            username: root
            password: LYdata240!
    lyresource:
        url: jdbc:mysql://192.168.12.252:3306/lyresource?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: LYdata240!


spring:
  redis:
    host: 192.168.12.246
    port: 6379


cache:
  shhzw: 43200
  verificationCode: 180
  userInfoUuidByMobile: 1800
  securityCode: 1800
  payCode: 300
  token: 21600
logging:
  path: ../logs/haozuowenapi/
  file: ../logs/haozuowenapi

multipart :
  max-file-size: 20Mb
  max-request-size: 20Mb

reading:
  user:
    gold:
      initNum: 100
  registerUser:
    gold:
      initNum: 100

goldcoin:
  bookgoldcoin: 10

weixin:
  key: 6c0c956445914c858e3990ff82fb236f
  appID: wxb19eb092a6d891af
  mchID: 1318708701

alipay:
  partner: 2088511881019952
  sellerId: 2088511881019952
  key: 5e6yuxe79abzq8j3wmo7ualn4u7nay3w
  notify:
    url: http://liweipower2015.imwork.net:25388/pay/notify/
  return:
    url: http://www.lyced.com/ui/cp/alpha/#booklist